"""Masks that shatter into many disconnected components.

Most real objects are connected. A mask with 20 tiny blobs usually means:
- The labeler used brush-with-holes incorrectly.
- The mask was generated by a click-through tool that produced stray pixels.
- Two different objects got merged under one annotation.

Any of these hurts training.
"""
from __future__ import annotations

from typing import List

from lightly_insights.core.check import Check, register_check
from lightly_insights.core.dataset import AnnotationKind, Dataset
from lightly_insights.core.finding import Finding, Severity
from lightly_insights.core.geometry import Mask

# Any single component smaller than this many pixels is treated as noise —
# isolated pixels shouldn't by themselves push a mask into "fragmented".
MIN_SIGNIFICANT_COMPONENT_AREA = 4
# Mask is flagged as fragmented if it has more than this many *significant*
# components.
MAX_SIGNIFICANT_COMPONENTS = 3


@register_check
class MaskFragmentationCheck(Check):
    check_id = "mask_fragmentation"
    title = "Fragmented mask"
    category = "annotation"
    supported_kinds = frozenset({AnnotationKind.MASK})

    def run(self, dataset: Dataset) -> List[Finding]:
        findings: List[Finding] = []
        for ann in dataset.annotations:
            if ann.kind != AnnotationKind.MASK:
                continue
            mask = ann.geometry
            if not isinstance(mask, Mask):
                continue
            significant = _significant_components(
                mask, min_area=MIN_SIGNIFICANT_COMPONENT_AREA
            )
            if significant <= MAX_SIGNIFICANT_COMPONENTS:
                continue
            findings.append(
                Finding(
                    check_id=self.check_id,
                    severity=Severity.HIGH,
                    category=self.category,
                    title=(
                        f"Fragmented mask for class '{ann.class_name}'"
                    ),
                    detail=(
                        f"Mask on {ann.image_filename} has {significant} "
                        "significant connected components. Most real "
                        "objects are one connected region."
                    ),
                    action=(
                        "Inspect the mask. If it's one object, clean up the "
                        "stray fragments. If it's two objects, split into "
                        "separate annotations."
                    ),
                    affected_images=[ann.image_filename],
                    affected_annotations=[ann.annotation_id],
                    evidence={
                        "significant_components": significant,
                        "class_name": ann.class_name,
                    },
                )
            )
        return findings


def _significant_components(mask: Mask, min_area: int) -> int:
    """Count connected components with area >= min_area.

    Uses the same pure-numpy flood fill as Mask.connected_components but
    filters tiny specks so single stray pixels don't trigger the check.
    """
    import numpy as np

    arr = mask.array
    if arr.size == 0 or not arr.any():
        return 0
    visited = np.zeros_like(arr, dtype=bool)
    h, w = arr.shape
    count = 0
    for y in range(h):
        for x in range(w):
            if not arr[y, x] or visited[y, x]:
                continue
            size = 0
            stack = [(y, x)]
            while stack:
                cy, cx = stack.pop()
                if visited[cy, cx] or not arr[cy, cx]:
                    continue
                visited[cy, cx] = True
                size += 1
                if cy + 1 < h and not visited[cy + 1, cx]:
                    stack.append((cy + 1, cx))
                if cy > 0 and not visited[cy - 1, cx]:
                    stack.append((cy - 1, cx))
                if cx + 1 < w and not visited[cy, cx + 1]:
                    stack.append((cy, cx + 1))
                if cx > 0 and not visited[cy, cx - 1]:
                    stack.append((cy, cx - 1))
            if size >= min_area:
                count += 1
    return count
